### ISSUE TITLE
curve-fuse's memory usage is unlimited when enabling `fakes3`

### ISSUE THREAD

**Issue by wu-hanqing** [opencurve/curve#1593]
**Describe the bug (描述bug)**

the process runs for 30 minutes, and the memory usage is 17.7g

<img width="829" alt="image" src="https://user-images.githubusercontent.com/10327590/174514822-f99a7db0-9514-4df5-9aec-0520345e8353.png">

**To Reproduce (复现方法)**

client yaml

```yaml
s3.ak: curve
s3.sk: curveadmin
s3.endpoint: xxx
s3.bucket_name: vdbench
container_image: xxx
mdsOpt.rpcRetryOpt.addrs: xxx
log_dir: /data/curve/d261fe4e-ee1f-11ec-b701-6c92bf5e4d94/logs
diskCache.diskCacheType: 2
data_dir: /data/curve/d261fe4e-ee1f-11ec-b701-6c92bf5e4d94/cache
fuseClient.cto: false
fuseClient.enableMultiMountPointRename: false
s3.fakeS3: true
core_dir: /data/curve/d261fe4e-ee1f-11ec-b701-6c92bf5e4d94/core
```

vdbench profile

```
fsd=fsd1,anchor=${MOUNTPOINT}/d1,depth=1,width=10,files=50,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd2,anchor=${MOUNTPOINT}/d2,depth=1,width=10,files=50,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd3,anchor=${MOUNTPOINT}/d3,depth=1,width=10,files=50,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd4,anchor=${MOUNTPOINT}/d4,depth=1,width=10,files=50,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd5,anchor=${MOUNTPOINT}/d5,depth=1,width=10,files=50,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=99999999999999999,interval=1
```

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch: release2.3
commit id: 12ae8abb

**Additional context/screenshots (更多上下文/截图)**

before this, I also built curve-fuse from the master, and also faced the same problem

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/10327590/174515209-a99e0218-4f95-445f-9d04-259c929416e5.png">

curve-fuse used up the memory and got killed.
