### ISSUE TITLE
三节点部署失败

### ISSUE THREAD

**Issue by brucen1030** [opencurve/curve#163]
## General Question
使用https://github.com/opencurve/curve/releases/download/v1.0.0/curve_1.0.0+8b04e0ec.tar.gz， 
  
CentOS8下部署单节点成功，部署三节点在deploy etcd这步失败。  
具体是哪里生成的etcd.conf.yml并拷贝到其它主机的？在中控机以外的两台主机没有看到生成的etcd.conf.yml。
```
############################## deploy etcd ##############################
- name: prepare etcd
  hosts: etcd
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: "{{ sudo_user }}"
  become_flags: -iu {{ sudo_user }}
  tags:
    - etcd
  roles:
    - { role: install_package, package_name: etcd, install_with_deb: false, tags: install_etcd } // 我直接把etcd的下载包解压拷贝到/usr/bin下了
    - { role: generate_config, template_name: etcd.conf.yml, conf_path: "{{ etcd_config_path }}", tags: generage_config } // 三节点，etcd1（也是中控机）成功，etcd2和etcd3失败

```  
  
ansible-playbook -i server.ini deploy_curve.yml 失败如下  
```
TASK [generate_config : generate configuration file directly] ****************************************************************************************
fatal: [etcd3]: FAILED! => {"changed": false, "checksum": "d0ddc59580bbb243f260acea51c4a870449ecaf8", "msg": "Destination /etc/curve not writable"}
...ignoring
fatal: [etcd1]: FAILED! => {"changed": false, "checksum": "ed3f202012e267b199f35bc0c2d106bfb436a6a7", "msg": "Destination /etc/curve not writable"}
...ignoring
fatal: [etcd2]: FAILED! => {"changed": false, "checksum": "e02c13a758f55ac58ccbf3be5443e10833a72d91", "msg": "Destination /etc/curve not writable"}
...ignoring

TASK [generate_config : generate configuration file at /tmp] *****************************************************************************************
changed: [etcd1]
changed: [etcd2]
changed: [etcd3]

TASK [generate_config : mv config file] **************************************************************************************************************
changed: [etcd1]
fatal: [etcd2]: FAILED! => {"changed": true, "cmd": "sudo mv /tmp/etcd.conf.yml /etc/curve/etcd.conf.yml", "delta": "0:00:00.016609", "end": "2020-11-13 04:07:44.967946", "msg": "non-zero return code", "rc": 1, "start": "2020-11-13 04:07:44.951337", "stderr": "mv: cannot stat '/tmp/etcd.conf.yml': No such file or directory", "stderr_lines": ["mv: cannot stat '/tmp/etcd.conf.yml': No such file or directory"], "stdout": "", "stdout_lines": []}
fatal: [etcd3]: FAILED! => {"changed": true, "cmd": "sudo mv /tmp/etcd.conf.yml /etc/curve/etcd.conf.yml", "delta": "0:00:01.017238", "end": "2020-11-13 04:07:45.976883", "msg": "non-zero return code", "rc": 1, "start": "2020-11-13 04:07:44.959645", "stderr": "mv: cannot stat '/tmp/etcd.conf.yml': No such file or directory", "stderr_lines": ["mv: cannot stat '/tmp/etcd.conf.yml': No such file or directory"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT ***********************************************************************************************************************************
	to retry, use: --limit @/home/curve/curve/curve/curve-ansible/deploy_curve.retry

PLAY RECAP *******************************************************************************************************************************************
etcd1                      : ok=52   changed=14   unreachable=0    failed=0   
etcd2                      : ok=51   changed=13   unreachable=0    failed=1   
etcd3                      : ok=51   changed=13   unreachable=0    failed=1   
localhost                  : ok=35   changed=8    unreachable=0    failed=0   
mds1                       : ok=34   changed=8    unreachable=0    failed=0   
mds2                       : ok=34   changed=8    unreachable=0    failed=0   
mds3                       : ok=34   changed=8    unreachable=0    failed=0   
nginx1                     : ok=34   changed=8    unreachable=0    failed=0   
nginx2                     : ok=34   changed=8    unreachable=0    failed=0   
server1                    : ok=36   changed=8    unreachable=0    failed=0   
server2                    : ok=36   changed=8    unreachable=0    failed=0   
server3                    : ok=36   changed=8    unreachable=0    failed=0   
snap1                      : ok=34   changed=8    unreachable=0    failed=0   
snap2                      : ok=34   changed=8    unreachable=0    failed=0   
snap3                      : ok=34   changed=8    unreachable=0    failed=0   

```  
  
而在显示成功的etcd1（中控机）上，生成的etcd.conf.xml显示是etcd3？？？  
```
$ sudo head /etc/curve/etcd.conf.yml 
# This is the configuration file for the etcd server.

# Human-readable name for this member.
name: etcd3      <------------???

# Path to the data directory.
data-dir: /etcd/data

# Path to the dedicated wal directory.
wal-dir: /etcd/wal

```
