### ISSUE TITLE
Client crashes when running vdbench and cycling warmup

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2208]
**Describe the bug (描述bug)**

Client crashes when running vdbench and cycling warmup

**To Reproduce (复现方法)**

0.client.yaml
```yaml
kind: curvefs
s3.ak:*******
s3.sk: *******
s3.endpoint: *******
s3.bucket_name: *******
container_image: *******
mdsOpt.rpcRetryOpt.addrs: *******
log_dir: /home/nbs/curvefs/logs/client
data_dir: /home/nbs/curvefs/data/client/cache
client.loglevel: 0
# the max size disk cache can use
diskCache.maxUsableSpaceBytes: 1073741824000
# the max files that can cache
diskCache.maxFileNums: 100000000
```

1. vdbench
```shell
sudo ./vdbench -f profile -jn
```
profile:
```
fsd=fsd1,anchor=/home/nbs/curvefs/mnt/mnt-0,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=604800,interval=1
```
2. warmup 
warmup.sh:
```shell
for i in {1..6048};do
echo "warmup $i /home/nbs/curvefs/mnt/mnt-0"
sudo /home/nbs/curve fs warmup add /home/nbs/curvefs/mnt/mnt-0
sleep 100
done
```
then 
```shell
bash warmup.sh
```

Then the client will crash

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**
