### ISSUE TITLE
[curve/toos-v2]: add snapshot-clone-status

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2346]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `bs status snapshot` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

- The implementation of the old tool is here：https://github.com/opencurve/curve/blob/8d6caf78c0aad0e08d367f98da661a678d7eb3ec/src/tools/status_tool.cpp#L658-L685
- The old command input and out put:
```bash
curve_ops_tool snapshot-clone-status

-------
output:
SnapshotCloneServer status:
version: ***
current snapshot-clone-server: ***
online snapshot-clone-server list: ***
offline snapshot-clone-server list: ***
```
Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Describe the solution you'd like (描述你期望的解决方法)**

Add subcommand clinet to curve bs list.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Xinlong-Chen** [comment]
I am interested in this task, please assign it to me, thanks.

**Comment by ilixiaocui** [comment]
> Xinlong-Chen

welcome!

**Comment by Xinlong-Chen** [comment]
@Cyber-SiKu When I tried to understand this task, I found that this task is similar to the implementation of the `curve bs status mds` command.

But I have a little doubt about the implementation of `mds`.

---

In tools-v1: there need 3 RPC to get status(in `curve/src/tools/status_tool.cpp@PrintMdsStatus`):

1. `versionTool_->GetAndCheckMdsVersion(&version, &failedList)`
2. `mdsClient_->GetCurrentMds()`
3. `mdsClient_->GetMdsOnlineStatus(&onlineStatus)`

---

But this is different in tools-v2.

There are only 2 rpcs in tools-v2(in `curve/tools-v2/pkg/cli/command/curvebs/status/mds/mds.go@Init`):

1. `statusMetric := basecmd.NewMetric(addrs, STATUS_SUBURI, timeout)`
2. `versionMetric := basecmd.NewMetric(addrs, VERSION_SUBURI, timeout)`

---

This 2 rpcs in tools-v2 is the same as the first two rpcs in tools-v1. 

I would like to ask why it can be done like this (get rid of the tail rpc)?

**Comment by Cyber-SiKu** [comment]
> @Cyber-SiKu When I tried to understand this task, I found that this task is similar to the implementation of the `curve bs status mds` command.
> 
> But I have a little doubt about the implementation of `mds`.
> 
> In tools-v1: there need 3 rpcs to get status(in `curve/src/tools/status_tool.cpp@PrintMdsStatus`):
> 
> 1. `versionTool_->GetAndCheckMdsVersion(&version, &failedList)`
> 2. `mdsClient_->GetCurrentMds()`
> 3. `mdsClient_->GetMdsOnlineStatus(&onlineStatus)`
> 
> But this is different in tools-v2.
> 
> There are only 2 rpcs in tools-v2(in `curve/tools-v2/pkg/cli/command/curvebs/status/mds/mds.go@Init`):
> 
> 1. `statusMetric := basecmd.NewMetric(addrs, STATUS_SUBURI, timeout)`
> 2. `versionMetric := basecmd.NewMetric(addrs, VERSION_SUBURI, timeout)`
> 
> This 2 rpcs in tools-v2 is the same as the first two rpcs in tools-v1.
> 
> I would like to ask why it can be done like this (get rid of the tail rpc)?

GetCurrentMds
https://github.com/opencurve/curve/blob/4e73df5e4f0b05efb59ace232bd55ef1f9a8c42e/src/tools/mds_client.cpp#L973-L990

GetMdsOnlineStatus
https://github.com/opencurve/curve/blob/4e73df5e4f0b05efb59ace232bd55ef1f9a8c42e/src/tools/mds_client.cpp#L901-L925

**Comment by Xinlong-Chen** [comment]
**Got it!** 

Based on postmentioned reason, we also can implement `bs status snapshot` command with 2 rpcs.

There are the corresponding metric string I found about snapshot. I don't know if that's right?

```go
STATUS_SUBURI  = "/vars/snapshotcloneserver_status"
VERSION_SUBURI = "/vars/curve_version"
```

**Comment by Xinlong-Chen** [comment]
Well, I also have a question that how can I test it?
When I use tools-v1 command `curve_ops_tool snapshot-clone-status` in docker(use [reference](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) image)，the following result I get bothers me.
```
root@f8df310173eb:/# curve_ops_tool snapshot-clone-status
SnapshotCloneServer status:
No SnapshotCloneServer
```
Do I need do more action about snapshot deployment to get correct result as following:
```
curve_ops_tool snapshot-clone-status

-------
output:
SnapshotCloneServer status:
version: ***
current snapshot-clone-server: ***
online snapshot-clone-server list: ***
offline snapshot-clone-server list: ***
```

**Comment by Cyber-SiKu** [comment]
Currently snapshot-related commands cannot use the cluster deployed by curveadm palygroud (there is no s3, so there is no snapshot).
Need to [deploy](https://github.com/opencurve/curveadm/wiki/curvefs-cluster-deployment#%E7%AC%AC-3-%E6%AD%A5%E9%83%A8%E7%BD%B2-minio%E5%8F%AF%E9%80%89) a minio.
Then follow the [deployment document](https://github.com/opencurve/curveadm/wiki/curvebs-cluster-deployment) to deploy a stand-alone cluster. You can skip formatting the disk, and then fill in the configuration items of topology.yaml:
```yaml
kind: curvebs
global:
...
   s3.nos_address: <> // ip:9000 is the ip and port number deployed by minio
   s3.snapshot_bucket_name: <> // created bucket name
   s3.ak: <> // ak minioadmin
   s3.sk: <> //sk minioadmin
...

chunkserver_services:
   config:
...
     copiesets: 100
      chunkfilepool.enable_get_chunk_from_pool: false
   deploy:
     - host: ${target}
     - host: ${target}
     - host: ${target}
...
```

**Comment by Cyber-SiKu** [comment]
目前snapshot 相关的命令不能使用 curveadm palygroud 部署的集群(没有s3,所以没有snapshot).
需要先[部署](https://github.com/opencurve/curveadm/wiki/curvefs-cluster-deployment#%E7%AC%AC-3-%E6%AD%A5%E9%83%A8%E7%BD%B2-minio%E5%8F%AF%E9%80%89)一个minio.
然后按照[部署文档](https://github.com/opencurve/curveadm/wiki/curvebs-cluster-deployment)部署一个单机集群.可以跳过格式化磁盘,然后在填写topology.yaml的配置项:
```yaml
kind: curvebs
global:
... ...
  s3.nos_address: <> // ip:9000 为minio部署的ip和端口号
  s3.snapshot_bucket_name: <> // 创建的桶名
  s3.ak: <> // ak  minioadmin
  s3.sk: <> //sk minioadmin
... ...

chunkserver_services:
  config:
... ...
    copysets: 100
     chunkfilepool.enable_get_chunk_from_pool: false
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}
... ...
```
