### ISSUE TITLE
[curve/toos-v2]: add do-snapshot-all

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curve#2352]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

we'd like to support `bs snapshot ` command  in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)

- The implementation of the old tool is here：
https://github.com/opencurve/curve/blob/8d6caf78c0aad0e08d367f98da661a678d7eb3ec/src/tools/curve_cli.cpp#L291-L314
- The old command input and out put:
```bash
curve_ops_tool do-snapshot-all
-------
output:
```
Refer to [tool develop guide](https://github.com/opencurve/curve/blob/master/tools-v2/docs/zh/develop.md) to get start, and paste the result of the command in pr.

Build compilation environment：https://github.com/opencurve/curve/blob/master/docs/cn/build_and_run.md

**Describe the solution you'd like (描述你期望的解决方法)**

Add subcommand clinet to curve bs list.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by iiiuwioajdks** [comment]
I want to complete this task, can you assign it to me?

**Comment by Cyber-SiKu** [comment]
@iiiuwioajdks

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by Cyber-SiKu** [comment]
Currently snapshot-related commands cannot use the cluster deployed by curveadm palygroud (there is no s3, so there is no snapshot).
Need to [deploy](https://github.com/opencurve/curveadm/wiki/curvefs-cluster-deployment#%E7%AC%AC-3-%E6%AD%A5%E9%83%A8%E7% BD%B2-minio%E5%8F%AF%E9%80%89) a minio.
Then follow the [deployment document] (https://github.com/opencurve/curveadm/wiki/curvebs-cluster-deployment) to deploy a stand-alone cluster. You can skip formatting the disk, and then fill in the configuration items of topology.yaml:
```yaml
kind: curvebs
global:
...
   s3.nos_address: <> // ip:9000 is the ip and port number deployed by minio
   s3.snapshot_bucket_name: <> // created bucket name
   s3.ak: <> // ak minioadmin
   s3.sk: <> //sk minioadmin
...

chunkserver_services:
   config:
...
     copiesets: 100
      chunkfilepool.enable_get_chunk_from_pool: false
   deploy:
     - host: ${target}
     - host: ${target}
     - host: ${target}
...
```
